//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentJournalASPNET.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentClass
    {
        public StudentClass()
        {
            this.Student = new HashSet<Student>();
            this.TEACHERSCLASSes = new HashSet<TEACHERSCLASS>();
        }
    
        public int ClassId { get; set; }
        public string ClassName { get; set; }
    
        public virtual ICollection<Student> Student { get; set; }
        public virtual ICollection<TEACHERSCLASS> TEACHERSCLASSes { get; set; }
    }
}
