//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentJournalASPNET.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public Student()
        {
            this.StudentMarks = new HashSet<StudentMarks>();
        }
    
        public int id { get; set; }
        [Key]
        public string Pesel { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int GenderId { get; set; }
        public string BirthDate { get; set; }
        public int CityId { get; set; }
        public Nullable<int> ClassId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual StudentClass StudentClass { get; set; }
        public virtual ICollection<StudentMarks> StudentMarks { get; set; }
    }
}
