//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentJournalASPNET.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHERSCLASS
    {
        public int TEACHERCLASSID { get; set; }
        public int TEACHERID { get; set; }
        public int CLASSID { get; set; }
    
        public virtual StudentClass StudentClass { get; set; }
        public virtual TEACHER TEACHER { get; set; }
    }
}
